dataset:
  name: zinc
  path: /datapool/data2/home/pengxingang/zhangyijia/LinkerNet/data/zinc_difflinker
  version: full
  index_name: index_full.pkl
  max_num_atoms: 30
  split_mode: None

model:
  checkpoint: /datapool/data2/home/pengxingang/zhangyijia/LinkerNet/ckpt/zinc_model.pt

sample:
  seed: 2022
  num_samples: 100
  num_atoms: ref
  guidance_opt:
#  num_steps: 100
#  energy_drift:
#    - type: frag_link_prox
#      min_d: 1.2
#      max_d: 1.9
